#!/usr/bin/env bash
# A Bash script that displays a list of all currently running processes in a user-oriented, hierarchical format

ps -eo user,pid,ppid,%cpu,%mem,vsz,rss,tty,stat,start,time,cmd --forest
